spring:
  cache:
    type: simple
  datasource:
    url: jdbc:h2:mem:demodb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    com.example.demo: DEBUG
